name: Nextjs build with Caching and Artifacts
on:
   push:
       branches: [main]
jobs:
    build:
         runs-on: ubuntu-latest
         steps:
             - name: Checkout repository
               uses: actions/checkout@v6.0.2

             - name: Setup nodeJs    
               uses: actions/setup-node@v6.3.0
               with:
                 node-version: 22.x
                 cache: 'npm'
             - name: Install Dependencies
               run: npm install

             - name: Build NextJs App
               run: npm run build

             - name: Upload builds on Artifacts
               uses: actions/upload-artifact@v7.0.0
               with:
                  name: nextjs-build
                  path: .next/

             
